# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fusion_tables"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Tokumine", "Tom Verbeure"]
  s.date = "2013-01-14"
  s.description = "A simple Google Fusion Tables API wrapper. Supports bulk inserts and most API functions"
  s.email = "simon@tinypla.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.md",
    "Rakefile",
    "TODO.md",
    "VERSION",
    "examples/boris_bikes.rb",
    "examples/compare_tweets.rb",
    "examples/credentials.example.yml",
    "fusion_tables.gemspec",
    "lib/fusion_tables.rb",
    "lib/fusion_tables/client/fusion_tables.rb",
    "lib/fusion_tables/data/data.rb",
    "lib/fusion_tables/data/table.rb",
    "lib/fusion_tables/ext/fusion_tables.rb",
    "test/README",
    "test/helper.rb",
    "test/test_client.rb",
    "test/test_config.yml.sample",
    "test/test_ext.rb",
    "test/test_sql.rb",
    "test/test_table.rb"
  ]
  s.homepage = "http://github.com/tokumine/fusion_tables"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Google Fusion Tables API wrapper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<gdata_19>, [">= 1.1.2"])
      s.add_runtime_dependency(%q<json>, [">= 1.7.6"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<gdata_19>, [">= 1.1.2"])
      s.add_dependency(%q<json>, [">= 1.7.6"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<gdata_19>, [">= 1.1.2"])
    s.add_dependency(%q<json>, [">= 1.7.6"])
  end
end

